site_name: Streamkit Documentation
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            heading_level: 2
nav:
  - Home: index.md
  - API Reference: api.md
