site_name: Streamkit Documentation
site_dir: docs
docs_dir: docs_source

repo_url: https://github.com/avkoehl/streamkit
repo_name: avkoehl/streamkit

theme:
  name: readthedocs
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            heading_level: 3
  - mkdocs-jupyter:
      include_source: true
      execute: false 
nav:
  - Home: index.md
  - API Reference: api.md
  - Examples:
      - Downloading Data: 'data.ipynb'
      - Aligning NHD Data to DEM: 'align_nhd.ipynb'
      - Watershed Functions: 'watershed.ipynb'
      - Reach Delineation: 'reaches.ipynb'
      - Stream Network Analysis: 'network.ipynb'
      - Cross Sections: 'xs.ipynb'
